
import type { Building, Department, Room, Manufacturer, EquipmentType, Equipment, FundingSource } from './types';

export const BUILDINGS: Building[] = [
  { building_id: 1, building_code: 'MAIN', building_name: 'Main Hospital Building' },
  { building_id: 2, building_code: 'OUTPT', building_name: 'Outpatient Imaging Center' },
  { building_id: 3, building_code: 'EMRG', building_name: 'Emergency Department' },
];

export const DEPARTMENTS: Department[] = [
  { department_id: 1, dept_code: 'RA', dept_name: 'Radiology', building_id: 1 },
  { department_id: 2, dept_code: 'ER', dept_name: 'Emergency Radiology', building_id: 3 },
  { department_id: 3, dept_code: 'OI', dept_name: 'Outpatient Imaging', building_id: 2 },
  { department_id: 4, dept_code: 'NM', dept_name: 'Nuclear Medicine', building_id: 1 },
  { department_id: 5, dept_code: 'US', dept_name: 'Ultrasound', building_id: 1 },
];

export const ROOMS: Room[] = [
  { room_id: 1, room_code: '01', room_name: 'CT Scanner Room 1', department_id: 1, floor_number: 1 },
  { room_id: 2, room_code: '02', room_name: 'MRI Suite 1', department_id: 1, floor_number: 1 },
  { room_id: 3, room_code: '03', room_name: 'X-Ray Room 1', department_id: 1, floor_number: 1 },
  { room_id: 4, room_code: '04', room_name: 'Mammography Suite', department_id: 1, floor_number: 2 },
  { room_id: 5, room_code: '05', room_name: 'Ultrasound Room 1', department_id: 5, floor_number: 2 },
  { room_id: 6, room_code: '06', room_name: 'DEXA Room', department_id: 1, floor_number: 1 },
];

export const MANUFACTURERS: Manufacturer[] = [
  { manufacturer_id: 1, manufacturer_code: 'GE', manufacturer_name: 'GE Healthcare' },
  { manufacturer_id: 2, manufacturer_code: 'SIE', manufacturer_name: 'Siemens Healthineers' },
  { manufacturer_id: 3, manufacturer_code: 'PHI', manufacturer_name: 'Philips Healthcare' },
  { manufacturer_id: 4, manufacturer_code: 'HIT', manufacturer_name: 'Hitachi Medical' },
  { manufacturer_id: 5, manufacturer_code: 'CAN', manufacturer_name: 'Canon Medical Systems' },
  { manufacturer_id: 6, manufacturer_code: 'HOL', manufacturer_name: 'Hologic Inc.' },
];

export const EQUIPMENT_TYPES: EquipmentType[] = [
  { equipment_type_id: 1, type_code: 'XRA', type_name: 'X-Ray System', gmdn_code: '37644' },
  { equipment_type_id: 2, type_code: 'MRI', type_name: 'MRI Scanner', gmdn_code: '37708' },
  { equipment_type_id: 3, type_code: 'CTX', type_name: 'CT Scanner', gmdn_code: '37975' },
  { equipment_type_id: 4, type_code: 'USC', type_name: 'Ultrasound System', gmdn_code: '13275' },
  { equipment_type_id: 5, type_code: 'MAM', type_name: 'Mammography System', gmdn_code: '37672' },
  { equipment_type_id: 6, type_code: 'DXA', type_name: 'DEXA Scanner', gmdn_code: '36987' },
];

export const FUNDING_SOURCES: FundingSource[] = [
    { funding_id: 1, funding_code: 'CAP-2024-001', funding_name: 'Capital Equipment Fund 2024' },
    { funding_id: 2, funding_code: 'GRANT-NIH-001', funding_name: 'NIH Research Grant' },
    { funding_id: 3, funding_code: 'DON-SMITH-001', funding_name: 'Smith Family Foundation' },
    { funding_id: 4, funding_code: 'LEASE-2024', funding_name: 'Equipment Lease Program' },
];

export const EQUIPMENT_DATA: Equipment[] = [
  {
    equipment_id: 1,
    inventory_code: 'XRA-RA-1-01-0001',
    equipment_name: 'Digital Radiography System',
    equipment_type_id: 1,
    manufacturer_id: 1,
    model_number: 'Discovery XR656',
    serial_number: 'GE12345XR001',
    year_manufactured: 2023,
    purchase_date: '2023-03-15',
    installation_date: '2023-04-10',
    commissioning_date: '2023-04-15',
    warranty_expiry_date: '2026-03-15',
    purchase_price: 285000.00,
    current_value: 250000.00,
    ownership_type: 'OWNED',
    room_id: 3,
    equipment_status: 'ACTIVE',
    condition_rating: 'EXCELLENT',
    last_maintenance_date: '2024-06-10',
    next_maintenance_date: '2024-09-10',
    maintenance_frequency_days: 90,
    funding_id: 1,
  },
  {
    equipment_id: 2,
    inventory_code: 'MRI-RA-1-02-0001',
    equipment_name: '3.0T MRI Scanner',
    equipment_type_id: 2,
    manufacturer_id: 2,
    model_number: 'MAGNETOM Vida',
    serial_number: 'SIE67890MR001',
    year_manufactured: 2022,
    purchase_date: '2022-08-20',
    installation_date: '2022-10-15',
    commissioning_date: '2022-11-01',
    warranty_expiry_date: '2025-08-20',
    purchase_price: 2500000.00,
    current_value: 2200000.00,
    ownership_type: 'OWNED',
    room_id: 2,
    equipment_status: 'ACTIVE',
    condition_rating: 'GOOD',
    last_maintenance_date: '2024-05-01',
    next_maintenance_date: '2024-11-01',
    maintenance_frequency_days: 180,
    funding_id: 2,
  },
  {
    equipment_id: 3,
    inventory_code: 'CTX-RA-1-01-0001',
    equipment_name: '128-Slice CT Scanner',
    equipment_type_id: 3,
    manufacturer_id: 1,
    model_number: 'Revolution CT',
    serial_number: 'GE54321CT001',
    year_manufactured: 2024,
    purchase_date: '2024-01-10',
    installation_date: '2024-02-20',
    commissioning_date: '2024-03-01',
    warranty_expiry_date: '2027-01-10',
    purchase_price: 1800000.00,
    current_value: 1800000.00,
    ownership_type: 'OWNED',
    room_id: 1,
    equipment_status: 'ACTIVE',
    condition_rating: 'EXCELLENT',
    last_maintenance_date: '2024-06-01',
    next_maintenance_date: '2024-09-01',
    maintenance_frequency_days: 90,
    funding_id: 1,
  },
  {
    equipment_id: 4,
    inventory_code: 'MAM-RA-2-04-0001',
    equipment_name: '3D Mammography System',
    equipment_type_id: 5,
    manufacturer_id: 6,
    model_number: 'Selenia Dimensions',
    serial_number: 'HOL98765MAM01',
    year_manufactured: 2021,
    purchase_date: '2021-11-01',
    installation_date: '2021-11-20',
    commissioning_date: '2021-12-01',
    warranty_expiry_date: '2024-11-01',
    purchase_price: 450000.00,
    current_value: 350000.00,
    ownership_type: 'OWNED',
    room_id: 4,
    equipment_status: 'MAINTENANCE',
    condition_rating: 'GOOD',
    last_maintenance_date: '2024-07-01',
    next_maintenance_date: '2025-01-01',
    maintenance_frequency_days: 180,
    funding_id: 3,
  },
  {
    equipment_id: 5,
    inventory_code: 'USC-US-2-05-0001',
    equipment_name: 'General Ultrasound System',
    equipment_type_id: 4,
    manufacturer_id: 3,
    model_number: 'EPIQ Elite',
    serial_number: 'PHI24680US01',
    year_manufactured: 2023,
    purchase_date: '2023-05-10',
    installation_date: '2023-05-15',
    commissioning_date: '2023-05-16',
    warranty_expiry_date: '2026-05-10',
    purchase_price: 150000.00,
    current_value: 135000.00,
    ownership_type: 'LEASED',
    room_id: 5,
    equipment_status: 'ACTIVE',
    condition_rating: 'EXCELLENT',
    last_maintenance_date: '2024-05-15',
    next_maintenance_date: '2025-05-15',
    maintenance_frequency_days: 365,
    funding_id: 4,
  },
   {
    equipment_id: 6,
    inventory_code: 'XRA-ER-1-03-0002',
    equipment_name: 'Mobile X-Ray Unit',
    equipment_type_id: 1,
    manufacturer_id: 2,
    model_number: 'Mobilett Elara Max',
    serial_number: 'SIE55555XR02',
    year_manufactured: 2020,
    purchase_date: '2020-09-01',
    installation_date: '2020-09-05',
    commissioning_date: '2020-09-06',
    warranty_expiry_date: '2023-09-01',
    purchase_price: 180000.00,
    current_value: 110000.00,
    ownership_type: 'OWNED',
    room_id: 3, // Assuming it's based in an X-Ray room in ER
    equipment_status: 'OUT_OF_SERVICE',
    condition_rating: 'POOR',
    last_maintenance_date: '2024-02-15',
    next_maintenance_date: '2024-08-15',
    maintenance_frequency_days: 180,
    funding_id: 1,
  },
  {
    equipment_id: 7,
    inventory_code: 'DXA-RA-1-06-0001',
    equipment_name: 'Bone Densitometer',
    equipment_type_id: 6,
    manufacturer_id: 6,
    model_number: 'Horizon DXA',
    serial_number: 'HOL11223DXA01',
    year_manufactured: 2022,
    purchase_date: '2022-07-20',
    installation_date: '2022-08-01',
    commissioning_date: '2022-08-02',
    warranty_expiry_date: '2025-07-20',
    purchase_price: 95000.00,
    current_value: 80000.00,
    ownership_type: 'OWNED',
    room_id: 6,
    equipment_status: 'ACTIVE',
    condition_rating: 'EXCELLENT',
    last_maintenance_date: '2024-07-15',
    next_maintenance_date: '2024-08-12', // Due soon
    maintenance_frequency_days: 365,
    funding_id: 3,
  }
];

// --- PERFORMANCE OPTIMIZATION: Pre-computed Maps for fast lookups ---
export const BUILDING_MAP = new Map<number, Building>(BUILDINGS.map(b => [b.building_id, b]));
export const DEPARTMENT_MAP = new Map<number, Department>(DEPARTMENTS.map(d => [d.department_id, d]));
export const ROOM_MAP = new Map<number, Room>(ROOMS.map(r => [r.room_id, r]));
export const MANUFACTURER_MAP = new Map<number, Manufacturer>(MANUFACTURERS.map(m => [m.manufacturer_id, m]));
export const EQUIPMENT_TYPE_MAP = new Map<number, EquipmentType>(EQUIPMENT_TYPES.map(et => [et.equipment_type_id, et]));
export const FUNDING_SOURCE_MAP = new Map<number, FundingSource>(FUNDING_SOURCES.map(fs => [fs.funding_id, fs]));
